"""Example demonstrating the @lazy_class decorator.
This example shows how to use @lazy_class to generate class implementations
at runtime using an LLM.
⚠️ WARNING: This will modify this file when you run it!
Make sure you have committed your changes to git first.
"""
from lazy_impl import lazy_class
@lazy_class("Implement an LRU (Least Recently Used) cache with the following methods: "
            "get(key) -> value or None, put(key, value), and a max_size parameter in __init__")
class LRUCache:
    """LRU Cache implementation.
    This implementation will be generated by an LLM on first instantiation.
    """
    pass
@lazy_class("Implement a simple key-value store with TTL (time to live). "
            "Methods: set(key, value, ttl_seconds), get(key) -> value or None, "
            "delete(key), and automatic expiration of old entries")
class TTLStore:
    """Key-value store with time-to-live support.
    This implementation will be generated by an LLM on first instantiation.
    """
    pass
if __name__ == "__main__":
    # Make sure you have set ANTHROPIC_API_KEY or OPENAI_API_KEY
    print("Testing LRU Cache...")
    cache = LRUCache(max_size=3)
    cache.put("a", 1)
    cache.put("b", 2)
    cache.put("c", 3)
    print(f"Get 'a': {cache.get('a')}")
    cache.put("d", 4)  # Should evict 'b'
    print(f"Get 'b' (should be None): {cache.get('b')}")
    print("\nTesting TTL Store...")
    import time
    store = TTLStore()
    store.set("temp", "value", ttl_seconds=2)
    print(f"Get 'temp' immediately: {store.get('temp')}")
    time.sleep(3)
    print(f"Get 'temp' after 3 seconds (should be None): {store.get('temp')}")
    print("\n⚠️ Check this file - it has been modified with generated implementations!")
