"""Example demonstrating the @lazy decorator with functions.
This example shows how to use @lazy to generate function implementations
at runtime using an LLM.
⚠️ WARNING: This will modify this file when you run it!
Make sure you have committed your changes to git first.
"""
from lazy_impl import lazy
@lazy("Implement a quicksort algorithm that sorts a list in ascending order")
def quicksort(arr: list[int]) -> list[int]:
    """Sort a list using quicksort algorithm.
    This implementation will be generated by an LLM on first call.
    """
    pass
@lazy("Implement a function that calculates fibonacci numbers recursively with memoization")
def fibonacci(n: int) -> int:
    """Calculate the nth fibonacci number.
    This implementation will be generated by an LLM on first call.
    """
    pass
if __name__ == "__main__":
    # Make sure you have set ANTHROPIC_API_KEY or OPENAI_API_KEY
    print("Testing quicksort...")
    result = quicksort([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
    print(f"Sorted: {result}")
    print("\nTesting fibonacci...")
    result = fibonacci(10)
    print(f"Fibonacci(10) = {result}")
    print("\n⚠️ Check this file - it has been modified with generated implementations!")
