"""lazy-impl: Experimental LLM-powered code generation decorators.
⚠️ WARNING: This package generates code at runtime using LLMs and writes it
to your source files. Use at your own risk. Always use version control.
This package provides decorators that use Large Language Models to generate
Python code implementations at runtime:
- @lazy: Smart decorator that works with both functions and classes
- @lazy_fn: Explicit decorator for functions
- @lazy_class: Explicit decorator for classes
Example:
    from lazy_impl import lazy
    @lazy("Implement a quicksort algorithm")
    def quicksort(arr: list[int]) -> list[int]:
        pass  # Implementation generated by LLM on first call
    result = quicksort([3, 1, 4, 1, 5, 9, 2, 6])
Requirements:
    - Set ANTHROPIC_API_KEY or OPENAI_API_KEY environment variable
    - Use version control (git) before using these decorators
    - Review all generated code before committing
See README.md for full documentation and warnings.
"""
from .decorators import lazy, lazy_fn, lazy_class
__version__ = "0.1.0"
__all__ = ["lazy", "lazy_fn", "lazy_class"]
# Print warning on import
import warnings
warnings.warn(
    "\n" + "="*80 + "\n"
    "⚠️  WARNING: lazy-impl generates code at runtime using LLMs\n"
    "⚠️  This package MODIFIES YOUR SOURCE FILES automatically\n"
    "⚠️  Use ONLY in experimental projects with version control\n"
    "⚠️  Review all generated code before committing\n"
    "⚠️  NOT suitable for production use\n"
    + "="*80,
    UserWarning,
    stacklevel=2
)
