"""Lazy implementation decorators using LLMs for runtime code generation.
⚠️ WARNING: This module generates code at runtime using LLMs and writes it
to your source files. Use at your own risk. Always use version control.
This module provides decorators that use Large Language Models to generate
Python code implementations at runtime:
- @lazy: Smart decorator that works with both functions and classes
- @lazy_fn: Explicit decorator for functions
- @lazy_class: Explicit decorator for classes
The decorators analyze function/class signatures and docstrings, call an LLM
to generate implementation, write the generated code back to the source file,
and execute it.
Example:
    from lazy_impl import lazy
    @lazy("Implement a quicksort algorithm")
    def quicksort(arr: list[int]) -> list[int]:
        pass  # Implementation will be generated by LLM
    result = quicksort([3, 1, 4, 1, 5, 9, 2, 6])
"""
import ast
import inspect
import logging
import os
import re
import textwrap
from functools import wraps
from typing import Any, Callable, List, Optional, Tuple, Type
# Configure logging
logging.basicConfig(level=logging.WARNING, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
def remove_code_blocks(text: str) -> Tuple[List[str], List[str]]:
    """Extract code blocks and language labels from markdown-formatted text.
    Parameters:
        text (str): Markdown-formatted text containing code blocks
    Returns:
        Tuple[List[str], List[str]]: A tuple containing:
            - List[str]: Extracted code blocks with whitespace trimmed
            - List[str]: Language labels (empty string if no label specified)
    """
    pattern = r"```(\w*)\s*([\s\S]*?)```"
    matches = re.findall(pattern, text)
    code_blocks = [match[1].strip() for match in matches]
    labels = [match[0].strip() for match in matches]
    return code_blocks, labels
def lazy_fn(prompt: Optional[str] = None, bot: Optional[Any] = None, context: Optional[str] = None) -> Callable:
    """Decorator that lazily implements a function using an LLM at runtime.
    ⚠️ WARNING: This decorator generates code at runtime and writes it to your source file.
    Parameters:
        prompt (Optional[str]): Additional instructions for the LLM about how to implement
            the function. Defaults to empty string.
        bot (Optional[Any]): The bot instance to use for implementation. Defaults to
            a new AnthropicBot instance. Must have a respond() method.
        context (Optional[str]): Level of context to provide to the LLM. Options are:
            - 'None': No additional context (default)
            - 'low': Only the containing class
            - 'medium': The entire current file
            - 'high': Current file and interfaces of other files in directory
            - 'very high': All Python files in directory
    Returns:
        Callable: A decorator function that wraps the target function
    Example:
        @lazy_fn("Sort using a funny algorithm. Name variables as though you're a clown.")
        def sort(arr: list[int]) -> list[int]:
            pass
    """
    def decorator(func: Callable) -> Callable:
        """Inner decorator function that sets up the lazy implementation."""
        nonlocal bot, prompt, context
        if bot is None:
            # Try to import from bots package
            try:
                from bots import AnthropicBot
                bot = AnthropicBot(name="Claude")
            except ImportError:
                raise ImportError(
                    "lazy-impl requires the 'bots' package for LLM interaction. "
                    "Install it with: pip install bots"
                )
        if prompt is None:
            prompt = ""
        if context is None:
            context = "None"
        def wrapper(*args: Any, **kwargs: Any) -> Any:
            """Wrapper function that handles lazy function implementation."""
            nonlocal func
            if not hasattr(wrapper, "initialized") or not wrapper.initialized:
                function_name: str = func.__name__
                logger.debug(f"Initializing lazy function: {function_name}")
                context_content = _get_context(func, context)
                instructions: str = textwrap.dedent(
                    """Please fill out the following
                    function definition according to the following requirements.
                    Respond only with the code in a single code block. Include all
                    import statements inside the function definition. Remove the lazy
                    decorator. Respond only with the function definition, including
                    any new decorators and docstring. Include 'gen by @lazy' in the
                    docstring. Use PEP8 convention with type hints for all variables."""
                )
                complete_prompt: str = textwrap.dedent(
                    f"""
                    {instructions}
                    {prompt}
                    {context_content}
                    {function_name}{str(inspect.signature(func))}"""
                )
                response: str = bot.respond(complete_prompt)
                function_code, _ = remove_code_blocks(response)
                function_code = function_code[0]
                logger.debug(f"Generated function code:\n{function_code}")
                source_file: str = inspect.getfile(func)
                logger.debug(f"Source file: {source_file}")
                with open(source_file, "r", encoding="utf-8") as file:
                    source_lines: str = file.read()
                logger.debug(f"Original source file content:\n{source_lines}")
                source_tree: ast.AST = ast.parse(source_lines)
                class FunctionReplacer(ast.NodeTransformer):
                    """AST transformer that replaces a function definition with new code."""
                    def __init__(self, function_name: str, new_code: str):
                        self.function_name = function_name
                        self.new_code = new_code
                    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.AST:
                        """Visits a function definition node and replaces it if it matches."""
                        if node.name == self.function_name:
                            logger.debug(f"Replacing function: {self.function_name}")
                            new_node: ast.AST = ast.parse(self.new_code).body[0]
                            return new_node
                        return node
                function_replacer = FunctionReplacer(function_name, function_code)
                new_tree: ast.AST = function_replacer.visit(source_tree)
                ast.fix_missing_locations(new_tree)
                new_source_lines: str = ast.unparse(new_tree)
                logger.debug(f"New source file content:\n{new_source_lines}")
                with open(source_file, "w", encoding="utf-8") as file:
                    file.write(new_source_lines)
                logger.debug("Updated source file written")
                exec(function_code, globals())
                func = globals()[function_name]
                wrapper.initialized = True
                logger.debug(f"Lazy function {function_name} initialized")
            return func(*args, **kwargs)
        wrapper.initialized = False
        return wrapper
    return decorator
def lazy_class(prompt: Optional[str] = None, bot: Optional[Any] = None, context: Optional[str] = None) -> Callable:
    """Decorator that lazily implements a class using an LLM at runtime.
    ⚠️ WARNING: This decorator generates code at runtime and writes it to your source file.
    Parameters:
        prompt (Optional[str]): Additional instructions for the LLM about how to implement
            the class. Defaults to empty string.
        bot (Optional[Any]): The bot instance to use for implementation. Defaults to
            a new AnthropicBot instance. Must have a respond() method.
        context (Optional[str]): Level of context to provide to the LLM. Options are:
            - 'None': No additional context (default)
            - 'low': Only the containing module's imports and global variables
            - 'medium': The entire current file
            - 'high': Current file and interfaces of other files in directory
            - 'very high': All Python files in directory
    Returns:
        Callable: A decorator function that wraps the target class
    Example:
        @lazy_class("Implement a key-value store with Redis-like functionality")
        class DataStore:
            pass  # Will be implemented by LLM
    """
    def decorator(cls: Type) -> Type:
        """Inner decorator function that sets up the lazy class implementation."""
        nonlocal bot, prompt, context
        if bot is None:
            # Try to import from bots package
            try:
                from bots import AnthropicBot
                bot = AnthropicBot(name="Claude")
            except ImportError:
                raise ImportError(
                    "lazy-impl requires the 'bots' package for LLM interaction. "
                    "Install it with: pip install bots"
                )
        if prompt is None:
            prompt = ""
        if context is None:
            context = "None"
        # Store the original __new__ method
        original_new = cls.__new__
        @wraps(original_new)
        def new_new(cls_self, *args, **kwargs):
            """Replacement for __new__ that handles lazy class implementation."""
            if not hasattr(cls, "_lazy_initialized") or not cls._lazy_initialized:
                class_name: str = cls.__name__
                logger.debug(f"Initializing lazy class: {class_name}")
                # Get context for the class
                context_content = _get_context(cls, context)
                # Create prompt for LLM
                instructions: str = textwrap.dedent(
                    """Please implement the following class according to these requirements.
                    Respond only with the code in a single code block. Include all
                    import statements inside the class definition. Remove the lazy_class
                    decorator. Respond only with the class definition, including
                    any new decorators and docstring. Include 'gen by @lazy' in the
                    docstring. Use PEP8 convention with type hints."""
                )
                # Get the original class source code
                try:
                    original_class_code = inspect.getsource(cls)
                except (TypeError, OSError):
                    # Fall back to a basic class definition if source can't be retrieved
                    original_class_code = f"class {class_name}:\n    pass"
                complete_prompt: str = textwrap.dedent(
                    f"""
                    {instructions}
                    {prompt}
                    {context_content}
                    {original_class_code}"""
                )
                # Get implementation from LLM
                response: str = bot.respond(complete_prompt)
                class_code, _ = remove_code_blocks(response)
                class_code = class_code[0]
                logger.debug(f"Generated class code:\n{class_code}")
                # Update source file with new implementation
                source_file: str = inspect.getfile(cls)
                logger.debug(f"Source file: {source_file}")
                with open(source_file, "r", encoding="utf-8") as file:
                    source_lines: str = file.read()
                logger.debug(f"Original source file content:\n{source_lines}")
                source_tree: ast.AST = ast.parse(source_lines)
                class ClassReplacer(ast.NodeTransformer):
                    """AST transformer that replaces a class definition with new code."""
                    def __init__(self, class_name: str, new_code: str):
                        self.class_name = class_name
                        self.new_code = new_code
                    def visit_ClassDef(self, node: ast.ClassDef) -> ast.AST:
                        """Visits a class definition node and replaces it with new code if it matches."""
                        if node.name == self.class_name:
                            logger.debug(f"Replacing class: {self.class_name}")
                            new_node: ast.AST = ast.parse(self.new_code).body[0]
                            return new_node
                        return node
                class_replacer = ClassReplacer(class_name, class_code)
                new_tree: ast.AST = class_replacer.visit(source_tree)
                ast.fix_missing_locations(new_tree)
                new_source_lines: str = ast.unparse(new_tree)
                logger.debug(f"New source file content:\n{new_source_lines}")
                with open(source_file, "w", encoding="utf-8") as file:
                    file.write(new_source_lines)
                logger.debug("Updated source file written")
                # Execute the new class code
                module_globals = dict(globals())
                module_locals = {}
                exec(class_code, module_globals, module_locals)
                # Replace the current class with the new implementation
                new_cls = module_locals[class_name]
                # Copy all attributes from new_cls to cls
                for attr_name, attr_value in new_cls.__dict__.items():
                    if attr_name != "__dict__":
                        setattr(cls, attr_name, attr_value)
                # Mark as initialized
                cls._lazy_initialized = True
                logger.debug(f"Lazy class {class_name} initialized")
            # Call the original __new__ (which may have been replaced by the implementation)
            if hasattr(cls, "__new__") and cls.__new__ is not new_new:
                return cls.__new__(cls, *args, **kwargs)
            else:
                # Create a new instance with just the class
                instance = original_new(cls)
                # Then initialize it with the arguments
                if hasattr(instance, "__init__"):
                    instance.__init__(*args, **kwargs)
                return instance
        # Replace __new__ with our custom version
        cls.__new__ = new_new
        # Mark as not initialized
        cls._lazy_initialized = False
        return cls
    return decorator
def _get_context(obj: Any, context_level: str) -> str:
    """Retrieves contextual code based on the specified context level.
    Parameters:
        obj (Any): The function or class to get context for
        context_level (str): Level of context to retrieve
    Returns:
        str: The requested context as a string
    """
    if context_level == "None":
        return ""
    try:
        source_file = inspect.getfile(obj)
    except (TypeError, OSError):
        return ""
    source_dir = os.path.dirname(source_file)
    # Check if we're dealing with a function or class
    is_class = isinstance(obj, type)
    if context_level == "low":
        source_code = inspect.getsource(inspect.getmodule(obj))
        tree = ast.parse(source_code)
        if is_class:
            # For classes, return module imports and global variables
            imports_and_globals = []
            for node in tree.body:
                if isinstance(node, (ast.Import, ast.ImportFrom, ast.Assign)):
                    imports_and_globals.append(ast.unparse(node))
            return "\n".join(imports_and_globals)
        else:
            # For functions, return the containing class if applicable
            for node in ast.walk(tree):
                if isinstance(node, ast.ClassDef):
                    for sub_node in node.body:
                        if isinstance(sub_node, ast.FunctionDef) and sub_node.name == obj.__name__:
                            return ast.unparse(node)
            return ""
    elif context_level == "medium":
        with open(source_file, "r", encoding="utf-8") as file:
            return file.read()
    elif context_level == "high":
        context = ""
        with open(source_file, "r", encoding="utf-8") as file:
            context += f"Current file ({os.path.basename(source_file)}):\n{file.read()}\n\n"
        for filename in os.listdir(source_dir):
            if filename.endswith(".py") and filename != os.path.basename(source_file):
                file_path = os.path.join(source_dir, filename)
                context += f"Interface of {filename}:\n{_get_py_interface(file_path)}\n\n"
        return context
    elif context_level == "very high":
        context = ""
        for filename in os.listdir(source_dir):
            if filename.endswith(".py"):
                file_path = os.path.join(source_dir, filename)
                with open(file_path, "r", encoding="utf-8") as file:
                    context += f"File: {filename}\n{file.read()}\n\n"
        return context
    else:
        raise ValueError(f"Invalid context level: {context_level}")
def _get_py_interface(file_path: str) -> str:
    """Extracts the public interface (classes and functions) from a Python file.
    Parameters:
        file_path (str): Path to the Python file to analyze
    Returns:
        str: A string containing the module's interface
    """
    def get_docstring(node: ast.AST) -> str:
        """Extract docstring from an AST node."""
        return ast.get_docstring(node) or ""
    def format_function(node: ast.FunctionDef) -> str:
        """Format a function definition with its signature and docstring."""
        return f'def {node.name}{ast.unparse(node.args)}:\n    """{get_docstring(node)}"""\n'
    def format_class(node: ast.ClassDef) -> str:
        """Format a class definition with its signature, docstring, and method interfaces."""
        class_str = f"class {node.name}"
        if node.bases:
            class_str += f"({', '.join((ast.unparse(base) for base in node.bases))})"
        class_str += f':\n    """{get_docstring(node)}"""\n'
        for item in node.body:
            if isinstance(item, ast.FunctionDef):
                class_str += f"    {format_function(item)}\n"
        return class_str
    with open(file_path, "r", encoding="utf-8") as file:
        tree = ast.parse(file.read())
    interface = ""
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            interface += format_class(node) + "\n"
        elif isinstance(node, ast.FunctionDef):
            interface += format_function(node) + "\n"
    return interface.strip()
def lazy(prompt: Optional[str] = None, bot: Optional[Any] = None, context: Optional[str] = None) -> Callable:
    """Smart decorator that implements a function or class using an LLM at runtime.
    ⚠️ WARNING: This decorator generates code at runtime and writes it to your source file.
    This is a convenience decorator that automatically chooses between @lazy_fn and
    @lazy_class based on the type of the decorated object.
    Parameters:
        prompt (Optional[str]): Additional instructions for the LLM
        bot (Optional[Any]): The bot instance to use for implementation
        context (Optional[str]): Level of context to provide to the LLM
    Returns:
        Callable: A decorator that applies either lazy_fn or lazy_class
    Example:
        @lazy("Implement a sorting algorithm")
        def quicksort(items: list) -> list:
            pass  # Will be implemented by LLM
        @lazy("Implement a key-value store with TTL")
        class Cache:
            pass  # Will be implemented by LLM
    """
    def decorator(obj: Any) -> Any:
        """Inner decorator that dispatches to either lazy_fn or lazy_class."""
        if isinstance(obj, type):
            # If obj is a class, use lazy_class
            logger.debug(f"lazy: Detected class {obj.__name__}, using lazy_class")
            return lazy_class(prompt, bot, context)(obj)
        else:
            # Otherwise assume it's a function and use lazy_fn
            logger.debug(f"lazy: Detected function {obj.__name__}, using lazy_fn")
            return lazy_fn(prompt, bot, context)(obj)
    return decorator
# Alias for backwards compatibility
lazy_impl = lazy
